-- ═════════════════════════════════════════════════════════════════════
-- 1. حذف وإعادة بناء جدول الأصناف القديمة (old_items) بالهيكل الجديد المرن
-- ═════════════════════════════════════════════════════════════════════
DROP TABLE IF EXISTS public.old_items CASCADE;

CREATE TABLE public.old_items (
    id bigint generated by default as identity,
    item_code text,
    barcode text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint old_items_pkey primary key (id),
    constraint old_items_item_code_unique unique (item_code),
    constraint old_items_barcode_unique unique (barcode),
    constraint old_items_not_both_null check (item_code is not null or barcode is not null)
);

-- ═════════════════════════════════════════════════════════════════════
-- 2. إنشاء الفهارس (Indexes) لضمان سرعة البحث الفائقة لـ 46,000 صنف
-- ═════════════════════════════════════════════════════════════════════
CREATE INDEX IF NOT EXISTS idx_old_items_item_code ON public.old_items (item_code);
CREATE INDEX IF NOT EXISTS idx_old_items_barcode ON public.old_items (barcode);

-- ═════════════════════════════════════════════════════════════════════
-- 3. تفعيل Row Level Security (RLS) لحماية البيانات
-- ═════════════════════════════════════════════════════════════════════
ALTER TABLE public.old_items ENABLE ROW LEVEL SECURITY;

-- إزالة السياسات السابقة (إن وجدت) لمنع أي تضارب
DROP POLICY IF EXISTS "Allow authenticated read old_items" ON public.old_items;
DROP POLICY IF EXISTS "Admin full access old_items" ON public.old_items;

-- ═════════════════════════════════════════════════════════════════════
-- 4. إنشاء سياسات الحماية (RLS Policies)
-- ═════════════════════════════════════════════════════════════════════

-- أ. القراءة مسموحة لجميع المستخدمين الموثقين وغير المعلقين (ليتم التحقق في شاشة توثيق الطلبات)
CREATE POLICY "Allow authenticated read old_items" ON public.old_items
FOR SELECT TO authenticated USING (
    (auth.jwt() -> 'user_metadata' -> 'permissions' ->> '__is_suspended') IS DISTINCT FROM 'true' OR
    EXISTS (
        SELECT 1 FROM public.system_users u 
        WHERE u.id = auth.uid() AND (u.permissions ->> '__is_suspended') IS DISTINCT FROM 'true'
    )
);

-- ب. كامل الصلاحيات (إدخال، تعديل، حذف) مسموح فقط للأدمن أو من يملك صلاحيات تعديل صفحة الإدارة
CREATE POLICY "Admin full access old_items" ON public.old_items
FOR ALL TO authenticated USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' OR 
    (auth.jwt() -> 'user_metadata' -> 'permissions' -> 'admin' ->> 'edit') = 'true' OR
    EXISTS (
        SELECT 1 FROM public.system_users u 
        WHERE u.id = auth.uid() 
          AND (u.role = 'admin' OR (u.permissions -> 'admin' ->> 'edit') = 'true')
    )
) WITH CHECK (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' OR 
    (auth.jwt() -> 'user_metadata' -> 'permissions' -> 'admin' ->> 'edit') = 'true' OR
    EXISTS (
        SELECT 1 FROM public.system_users u 
        WHERE u.id = auth.uid() 
          AND (u.role = 'admin' OR (u.permissions -> 'admin' ->> 'edit') = 'true')
    )
);
